### ISSUE TITLE
cycle 1/2, 2/3, and 1/3 on half actions stopped working

### ISSUE THREAD

**Issue by dylanwebster** [rxhanson/Rectangle#1249]
When using keyboard shortcuts for "Left Half" or "Right Half", the "cycle 1/2, 2/3, and 1/3 on half actions" setting used to work to. cycle between 1/2, 2/3, and 1/3 the screen. Now, it cycles to 2/3 for a split second and then snaps back to 1/2. It does not cycle to 1/3 at all. I don't recall when exactly this broke and if it happened after a Rectangle or macOS update. 

macOS version: Ventura 13.4
Rectangle version: 0.70 (76)

**Comment by rxhanson** [comment]
Thanks for reporting. This sounds like you might have another window manager running at the same time? If that's not the case, would you mind adding logs for when this happens? Hold the option key in the menu bar menu and select View Logging...

**Comment by nleroy917** [comment]
Hello,

I also noticed that window snapping stopped working this morning after my MacBook updated to Ventura 13.4. This is the logging I see:

```
2023-09-01T07:20:46-04:00: Unable to obtain window id
2023-09-01T07:20:48-04:00: Unable to obtain window id
2023-09-01T07:20:50-04:00: Unable to obtain the accessibility element with the specified attribute at mouse location
2023-09-01T07:20:51-04:00: Unable to obtain the accessibility element with the specified attribute at mouse location
2023-09-01T07:20:52-04:00: Unable to obtain the accessibility element with the specified attribute at mouse location
```

This is the result of me attempting to snap to the right, then the left, then clicking the mouse three times.

**Comment by rxhanson** [comment]
Sometimes the accessibility API can be a little flaky immediately after an update, and this is often fixed by rebooting your Mac.

**Comment by nleroy917** [comment]
Got it.

AFK now but I'll try that as soon as possible.

**Comment by nleroy917** [comment]
Not sure if it solves @dylanwebster 's issue, but the restart did the trick.

Appreciate it!

**Comment by dylanwebster** [comment]
Thanks. So this appears to be intermittent and I haven't pinpointed it to what else is happening on my system. Randomly started working again yesterday and then stopped. Working again today after a reboot. To my knowledge, I don't have another window manager running. I'll try to grab logs if/when I see this again. 
Thanks by the way for making and maintaining rectangle. My life would be much worse without it ;)

**Comment by dylanwebster** [comment]
Hi Ryan, I'm still having issues, but it's more intermittent. 
Here's the log of moving between third when it works:
```
2023-09-18T16:59:13-07:00: AX sizing proposed: (640.0, 1055.0), result: (668.0, 1055.0)
2023-09-18T16:59:13-07:00: AX position proposed: (1280.0, 25.0), result: (1280.0, 25.0)
2023-09-18T16:59:13-07:00: AX sizing proposed: (640.0, 1055.0), result: (668.0, 1055.0)
2023-09-18T16:59:13-07:00: AX sizing proposed: (668.0, 1055.0), result: (668.0, 1055.0)
2023-09-18T16:59:13-07:00: AX position proposed: (1252.0, 25.0), result: (1252.0, 25.0)
2023-09-18T16:59:13-07:00: AX sizing proposed: (668.0, 1055.0), result: (668.0, 1055.0)
2023-09-18T16:59:13-07:00: rightHalf | display: (0.0, 0.0, 1920.0, 1055.0), calculatedRect: (1280.0, 25.0, 640.0, 1055.0), resultRect: (1252.0, 25.0, 668.0, 1055.0), srcScreen: DELL U2723QE, destScreen: DELL U2723QE, resultScreen: DELL U2723QE
2023-09-18T16:59:14-07:00: AX sizing proposed: (960.0, 1055.0), result: (668.0, 1055.0)
2023-09-18T16:59:14-07:00: AX position proposed: (960.0, 25.0), result: (960.0, 25.0)
2023-09-18T16:59:14-07:00: AX sizing proposed: (960.0, 1055.0), result: (960.0, 1055.0)
2023-09-18T16:59:14-07:00: rightHalf | display: (0.0, 0.0, 1920.0, 1055.0), calculatedRect: (960.0, 25.0, 960.0, 1055.0), resultRect: (960.0, 25.0, 960.0, 1055.0), srcScreen: DELL U2723QE, destScreen: DELL U2723QE, resultScreen: DELL U2723QE
2023-09-18T16:59:15-07:00: AX sizing proposed: (1280.0, 1055.0), result: (960.0, 1055.0)
2023-09-18T16:59:15-07:00: AX position proposed: (640.0, 25.0), result: (640.0, 25.0)
2023-09-18T16:59:15-07:00: AX sizing proposed: (1280.0, 1055.0), result: (1280.0, 1055.0)
2023-09-18T16:59:15-07:00: rightHalf | display: (0.0, 0.0, 1920.0, 1055.0), calculatedRect: (640.0, 25.0, 1280.0, 1055.0), resultRect: (640.0, 25.0, 1280.0, 1055.0), srcScreen: DELL U2723QE, destScreen: DELL U2723QE, resultScreen: DELL U2723QE

```
Here's a log of when it doesn't work
```
2023-09-19T07:36:10-07:00: Current frame is equal to new frame
2023-09-19T07:36:15-07:00: AX sizing proposed: (1280.0, 1055.0), result: (960.0, 1055.0)
2023-09-19T07:36:15-07:00: AX position proposed: (640.0, 25.0), result: (640.0, 25.0)
2023-09-19T07:36:15-07:00: AX sizing proposed: (1280.0, 1055.0), result: (1280.0, 1055.0)
2023-09-19T07:36:15-07:00: rightHalf | display: (0.0, 0.0, 1920.0, 1055.0), calculatedRect: (640.0, 25.0, 1280.0, 1055.0), resultRect: (640.0, 25.0, 1280.0, 1055.0), srcScreen: LG HDR 4K, destScreen: LG HDR 4K, resultScreen: LG HDR 4K
2023-09-19T07:36:19-07:00: Current frame is equal to new frame
2023-09-19T07:36:21-07:00: AX sizing proposed: (1280.0, 1055.0), result: (960.0, 1055.0)
2023-09-19T07:36:21-07:00: AX position proposed: (640.0, 25.0), result: (640.0, 25.0)
2023-09-19T07:36:21-07:00: AX sizing proposed: (1280.0, 1055.0), result: (1280.0, 1055.0)
2023-09-19T07:36:21-07:00: rightHalf | display: (0.0, 0.0, 1920.0, 1055.0), calculatedRect: (640.0, 25.0, 1280.0, 1055.0), resultRect: (640.0, 25.0, 1280.0, 1055.0), srcScreen: LG HDR 4K, destScreen: LG HDR 4K, resultScreen: LG HDR 4K
2023-09-19T07:37:12-07:00: AX sizing proposed: (960.0, 1055.0), result: (960.0, 1055.0)
2023-09-19T07:37:12-07:00: AX position proposed: (0.0, 25.0), result: (-0.0, 25.0)
2023-09-19T07:37:12-07:00: AX sizing proposed: (960.0, 1055.0), result: (960.0, 1055.0)
2023-09-19T07:37:12-07:00: leftHalf | display: (0.0, 0.0, 1920.0, 1055.0), calculatedRect: (0.0, 25.0, 960.0, 1055.0), resultRect: (-0.0, 25.0, 960.0, 1055.0), srcScreen: LG HDR 4K, destScreen: LG HDR 4K, resultScreen: LG HDR 4K
2023-09-19T07:37:14-07:00: AX sizing proposed: (1280.0, 1055.0), result: (1280.0, 1055.0)
2023-09-19T07:37:14-07:00: AX position proposed: (0.0, 25.0), result: (-0.0, 25.0)
2023-09-19T07:37:14-07:00: AX sizing proposed: (1280.0, 1055.0), result: (1280.0, 1055.0)
2023-09-19T07:37:14-07:00: leftHalf | display: (0.0, 0.0, 1920.0, 1055.0), calculatedRect: (0.0, 25.0, 1280.0, 1055.0), resultRect: (-0.0, 25.0, 1280.0, 1055.0), srcScreen: LG HDR 4K, destScreen: LG HDR 4K, resultScreen: LG HDR 4K
2023-09-19T07:37:33-07:00: Unable to obtain the accessibility element with the specified attribute at mouse location

```

I happened to be using two different monitors for this example, but the same behavior is independent of monitor used. What else would be useful information to troubleshoot? 

Also I'm now on 
macOS 13.5.2 and Rectangle 0.71

**Comment by dylanwebster** [comment]
I'm pretty sure I isolated the issue to DDM (Dell Display Manager) software that was doing something regardless of display. Not sure why it was intermittent, but now Rectangle is working consistently. Closing since I don't think there's an underlying Rectangle issue. Thanks!
